version: '3'

services:

  mysql:
    image: mysql/mysql-server:latest
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
    networks:
      - my-network2 

  ecommerce:
    image: adaulan/books-ecommerce
    ports:
      - 8081:8081
    networks:
      - my-network2

networks:
  my-network2:
    driver: bridge