FROM tomcat
RUN rm -rf /usr/local/tomcat/webapps/*
COPY ./target/books-ecommerce-1.0.war /usr/local/tomcat/webapps/ROOT.war
RUN mkdir classes
COPY ./target/classes /usr/local/tomcat/webapps/classes
CMD ["catalina.sh", "run"]
