/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Adaulan 
 * Created: 31/03/2020
 */
        CREATE DATABASE ECOMMERCE_PROJECT;

        USE ECOMMERCE_PROJECT;

        CREATE TABLE PRODUTOS(
        ID 		INT NOT NULL AUTO_INCREMENT,
        STATUS VARCHAR(1) NOT NULL DEFAULT 'A',
        TITULO	VARCHAR (255) NOT NULL,
        AUTOR		VARCHAR (255) NOT NULL,
        EDITORA		VARCHAR (255) NOT NULL,
        DESCRICAO	TEXT NOT NULL,
        IMAGEM LONGBLOB,
        IMAGEM1 LONGBLOB,
        IMAGEM2 LONGBLOB,
        VALORVENDA	FLOAT4 NOT NULL,
        VALORCUSTO	FLOAT4 NOT NULL,
        CATEGORIA	VARCHAR (30) NOT NULL,
        QUANTIDADE 	INT NOT NULL,
        DATACADASTRO    VARCHAR(255),
        NUMEROPAGINA INT,
        ACABAMENTO VARCHAR(255),
        IDIOMA VARCHAR(255),
        ALTURA VARCHAR(255),
        LARGURA VARCHAR(255),
        PESO FLOAT4,
        ISBN VARCHAR(255),
        TAG VARCHAR(255),
        CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID)
        );

        CREATE TABLE USUARIO(
        ID 		INT NOT NULL UNIQUE AUTO_INCREMENT,
        NOME 		VARCHAR(255) NOT NULL,
        USUARIO 	VARCHAR(255) UNIQUE NOT NULL,
        SENHA		VARCHAR(255) UNIQUE NOT NULL,
        EMAIL		VARCHAR (100) NOT NULL,
        TIPO		VARCHAR(255),
        DATANASC 	VARCHAR (10) NOT NULL,
        CELULAR		VARCHAR	(14),
        CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
        );
